> 什么是异步，JavaScript 中为了实现任务不阻碍其他代码执行的一种机制，实质上 JavaScript 还是单线程，只是为了让代码的执行顺序有所不同。

## 1. JavaScript 的异步实现方式

- 回调函数，缺点：容易产生回调地狱，代码耦合性太高，不易于维护

- Promise，缺点：有时造成多个 then 的链式调用，可能会造成代码的语义不够明确

- generator，可以在函数的执行过程中，将函数的执行权转移出去，在函数外部还可以将执行权转移回来。

- async，是 generator 的语法糖

## 2. setTimeout、Promise、Async/Await 的区别

### 1. setTimeout

```js
console.log("script start") //1. 打印 script start
setTimeout(function () {
  console.log("settimeout") // 4. 打印 settimeout
}) // 2. 调用 setTimeout 函数，并定义其完成后执行的回调函数
console.log("script end") //3. 打印 script start
// 输出顺序：script start->script end->settimeout
```

### 2. Promise

Promise 本身是一个同步的立即执行函数，当 executor 中执行 resolve 或者 reject 的时候，此时是异步操作，会先执行 then/catch 等，当主栈执行完成后，才会调用 resolve/reject 中存放的方法

```js
console.log("script start")
let promise1 = new Promise(function (resolve) {
  console.log("promise1")
  resolve()
  console.log("promise1 end")
}).then(function () {
  console.log("promise2")
})
setTimeout(function () {
  console.log("settimeout")
})
console.log("script end")
// 输出顺序: script start->promise1->promise1 end->script end->promise2->settimeout
```

执行顺序：

1. 主线程的任务，script start promise1
2. 碰到 resolve，将 promise1 的状态改为 resolved，并将结果保存下来
3. 执行 promise1 end
4. 碰到 promise1.then，放入微任务队列
5. 碰到 setTimeout，放入宏任务队列
6. 执行同步任务 script end
7. 同步任务执行完毕，执行任务队列中的任务，执行微任务队列中的任务，promise2
8. 微任务队列执行完毕，执行宏任务队列中的任务，settimeout
9. 任务全部完成，事件循环完成

### 3. async/await

async 函数返回一个 Promise 对象，当函数执行的时候，一旦遇到 await 就会先返回，等到触发的异步操作完成，在执行函数体后面的语句。理解：让出了线程，跳出了 async 函数体

```js
async function async1() {
  console.log("async1 start")
  await async2()
  console.log("async1 end")
}
async function async2() {
  console.log("async2")
}
console.log("script start")
async1()
console.log("script end")
// 输出顺序：script start->async1 start->async2->script end->async1 end
```

## 对 Promise 的理解

一个对象，保存着一个异步操作的结果。
Promise 是异步编程的一种解决方案，它是一个对象，可以获取异步操作的消息，他的出现大大改善了异步编程的困境，避免了地狱回调，它比传统的解决方案回调函数和事件更合理和更强大。

所谓 Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

### 1. 三种状态

- pending，进行中
- resolved，已完成
- rejected，已拒绝
  当一个任务交给 promise 的时候，他的状态就变成了 pending，完成就变成了 resolved

### 2. 两个过程

- pending -> fulfilled：resolved
- pending -> rejected：rejected

### promise 的缺点

- 无法取消，一旦建立，就会立即执行，无法中途取消
- 如果不设置回调函数，promise 内部抛出的错误，不会反映到外部
- 当处于 pending 状态时，无法得知目前进展到哪一个是阶段

**总结：**
Promise 对象是异步编程的一种解决方案。Promise 是一个构造函数，接收一个函数作为参数，返回一个 Promise 实例。一个 Promise 实例有三种状态，分别是 pending、resolved 和 rejected，分别代表了进行中、已成功和已失败。实例的状态只能由 pending 转变 resolved 或者 rejected 状态，并且状态一经改变，就凝固了，无法再被改变了。

状态的改变是通过 resolve() 和 reject() 函数来实现的，可以在异步操作结束后调用这两个函数改变 Promise 实例的状态，它的原型上定义了一个 then 方法，使用这个 then 方法可以为两个状态的改变注册回调函数。这个回调函数属于微任务，会在本轮事件循环的末尾执行。

## promise 的基本用法

### 1. 创建 promise 对象

```js
const promise = new Promise(function(resolve, reject) {
  // ... some code
  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```

一般情况下都会使用 new Promise()来创建 promise 对象，但是也可以使用 promise.resolve 和 promise.reject 这两个方法：

#### Promise.resolve

Promise.resolve(value)的返回值也是一个 promise 对象，可以对返回值进行.then 调用，代码如下：

```js
Promise.resolve(11).then(function (value) {
  console.log(value) // 打印出11
})
```

#### Promise.reject

Promise.reject 也是 new Promise 的快捷形式，也创建一个 promise 对象。代码如下：

```js
Promise.reject(new Error(“我错了，请原谅俺！！”));
// 两种方式一样
new Promise(function(resolve,reject){
   reject(new Error("我错了！"));
});
```

**下面是使用 resolve 和 reject 方法：**

```js
function testPromise(ready) {
  return new Promise(function (resolve, reject) {
    if (ready) resolve("hello")
    else reject("No,thanks")
  })
}

testPromise(true).then(
  function (res) {
    console.log(res) // hello
  },
  function (err) {
    console.log(err)
  }
)
```

### 2.Promise 方法

Promise 有五个常用的方法：then()、catch()、all()、race()、finally。

#### then()

当 Promise 执行的内容符合成功条件时，调用 resolve 函数，失败就调用 reject 函数。

```js
promise.then(
  function (value) {
    // success
  },
  function (error) {
    // failure
  }
)
```

then 方法可以接受两个回调函数作为参数。第一个回调函数是 Promise 对象的状态变为 resolved 时调用，第二个回调函数是 Promise 对象的状态变为 rejected 时调用。其中第二个参数可以省略。
then 方法返回的是一个新的 Promise 实例（不是原来那个 Promise 实例）。因此可以采用链式写法，即 then 方法后面再调用另一个 then 方法。

```js
let promise = new Promise((resolve, reject) => {
  ajax("first").success(function (res) {
    resolve(res)
  })
})
promise
  .then(res => {
    return new Promise((resovle, reject) => {
      ajax("second").success(function (res) {
        resolve(res)
      })
    })
  })
  .then(res => {
    return new Promise((resovle, reject) => {
      ajax("second").success(function (res) {
        resolve(res)
      })
    })
  })
  .then(res => {})
```

#### catch()

Promise 对象除了有 then 方法，还有一个 catch 方法，该方法相当于 then 方法的第二个参数，指向 reject 的回调函数。不过 catch 方法还有一个作用，就是在执行 resolve 回调函数时，如果出现错误，抛出异常，不会停止运行，而是进入 catch 方法中。

```js
p.then(
  data => {
    console.log("resolved", data)
  },
  err => {
    console.log("rejected", err)
  }
)
p.then(data => {
  console.log("resolved", data)
}).catch(err => {
  console.log("rejected", err)
})
```

#### all()

all 方法可以完成并行任务， 它接收一个数组，数组的每一项都是一个 promise 对象。当数组中所有的 promise 的状态都达到 resolved 的时候，all 方法的状态就会变成 resolved，如果有一个状态变成了 rejected，那么 all 方法的状态就会变成 rejected。

```js
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1)
  }, 2000)
})
let promise2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(2)
  }, 1000)
})
let promise3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(3)
  }, 3000)
})
Promise.all([promise1, promise2, promise3]).then(res => {
  console.log(res)
  //结果为：[1,2,3]
})
```
调用all方法时的结果成功的时候是回调函数的参数也是一个数组，这个数组按顺序保存着每一个promise对象resolve执行时的值。
